routes/web.php
<?php
 
use App\Data;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
 
Route::get('/home', 'HomeController@index')->name('home'); 
Route::get('/', 'HomeController@index'); 

Route::group(['prefix' => 'admin' , 'middleware' => 'admin'], function(){
    Route::Resource('/barang', 'BarangController');
    Route::Resource('/jenis', 'JenisController');
    Route::Resource('/ruang', 'RuangController');
    Route::Resource('/users', 'UserController');

    Route::get('/laporan/trs', 'LaporanController@transaksi');
    Route::get('/laporan/trs/pdf', 'LaporanController@transaksiPdf');
    Route::get('/laporan/trs/excel', 'LaporanController@transaksiExcel');

    Route::get('/laporan/barang', 'LaporanController@barang');
    Route::get('/laporan/barang/pdf', 'LaporanController@barangPdf');
    Route::get('/laporan/barang/excel', 'LaporanController@barangExcel');
});

Route::group(['prefix' => 'operator' , 'middleware' => 'operator'], function(){
    Route::get('/', 'OperatorController@index');
});

Route::Resource('/dashboard','DashboardController');
Route::Resource('/transaksi', 'TransaksiController');

Auth::routes();

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','nip','alamat',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

        /**
     * Method One To Many 
     */
    public function transaksi()
    {
    	return $this->hasMany(Transaksi::class);
    }

    public function inventaris()
    {
    	return $this->belongsTo(Inventaris::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Illuminate\Foundation\Auth\RegistersUsers;

class UserController extends Controller
{    
use RegistersUsers;
    protected $page = 'users';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        $no = 1;
        $page=$this->page;
        return view($this->page.'/index',compact('users','no','page'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
<<<<<<< HEAD
    {
        $page = $this->page;
        return view($this->page.'/create',compact('page'));
=======
    { 
        $page = $this->page;
        return view($this->page.'/create',compact('page','users'));
>>>>>>> third commit
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
     protected function validator(array $data)
     {
         return Validator::make($data, [
             'name' => ['required', 'string', 'max:30'],
             'email' => ['required', 'string', 'email', 'max:60', 'unique:users'],
             'password' => ['required', 'string', 'min:6', 'confirmed'],
             'nip' => ['required', 'string', 'max:20'],
             'alamat' => ['required', 'string', 'max:200'],
             'role' => ['required', 'string', 'max:200']
         ]);
     }

     
    public function store(Request $request)
    {
        $data=$request->all(); 
        
        if(count($request->name) > 0)
        {
            foreach($request->name as $item=>$v){
                $data2=array(
                    'name'=>$request->name[$item],
                    'email'=>$request->email[$item],
                    'nip'=>$request->nip[$item],
                    'alamat'=>$request->alamat[$item],
                    'role'=>$request->role[$item],
                    'password' => Hash::make($request->password[$item]),
                );
                User::insert($data2);
            }
        }
        return redirect('/admin/users');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user= User::find($id);
        $page = $this->page;
        return view($this->page.'/edit',compact('user','page'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        User::whereId($id)->update([
            'name' => $request->name,
            'email' => $request->email,
            'nip' => $request->nip,
            'alamat' => $request->alamat,
            'password' => Hash::make($request['password']),
            'role' => $request->role,
        ]);

        return redirect('/admin/'.$this->page);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::destroy($id);
        return redirect('/admin/users');
    }
}

resources/views/users/create.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Multiple data send</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
</head>
<body>
    <div class="container">
        <br>
        @if(Session::has('success'))
        <div class="alert alert-success">
            {{Session::get('success')}}
        </div>
        @endif
        <form action="/admin/users" method="POST">
            {{csrf_field()}}
            <section>
                <div class="panel panel-header">
                    
                    <div class="row">
<<<<<<< HEAD
                            </div></div>
                            <div class="panel panel-footer" >
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Nama</th>
                                            <th>Email</th>
                                            <th>Nip</th>
                                            <th>Alamat</th>
                                            <th>Bagian</th>
                                            <th>Password</th>
                                            <th><a href="#" class="addRow"><i class="glyphicon glyphicon-plus"></i></a></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td><input type="text" name="name[]" class="form-control" required=""></td>
                                                <td><input type="email" name="email[]" class="form-control" required=""></td>    
                                                <td><input type="text" name="nip[]" class="form-control" required=""></td>    
                                                <td><input type="text" name="alamat[]" class="form-control" required=""></td>    
                                                <td><input type="text" name="role[]" class="form-control" required=""></td>    
                                                <td><input type="text" name="password[]" class="form-control" required=""></td>    
                                                <td><a href="#" class="btn btn-danger remove"><i class="glyphicon glyphicon-remove"></i></a></td>
                                            </tr>
                                        </tr>
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <td style="border: none"></td>
                                            <td style="border: none"></td>
                                            <td style="border: none"></td>
                                            <td style="border: none"></td>
                                            <td style="border: none"></td>
                                            <td><input type="submit" name="" value="Submit" class="btn btn-success"></td>
                                        </tr>
                                    </tfoot>
                                </table>
                                <a href="{{route('users.index')}}" class="btn btn-warning pull-right">Back</a>
                            </div>
                        </section>
                    </form>
                </div>
                <script type="text/javascript">
                    $('tbody').delegate('.quantity,.budget','keyup',function(){
                        var tr=$(this).parent().parent();
                        var quantity=tr.find('.quantity').val();
                        var budget=tr.find('.budget').val();
                        var amount=(quantity*budget);
                        tr.find('.amount').val(amount);
                        total();
                    });
                    function total(){
                        var total=0;
                        $('.amount').each(function(i,e){
                            var amount=$(this).val()-0;
                            total +=amount;
                        });
                        $('.total').html(total+".00 tk");    
                    }
                    $('.addRow').on('click',function(){
                        addRow();
                    });
                    function addRow()
                    {
                        var tr='<tr>'+
                            '<td><input type="text" name="name[]" class="form-control" required=""></td>'+
                            '<td><input type="email" name="email[]" class="form-control" required=""></td>'+   
                            '<td><input type="text" name="nip[]" class="form-control" required=""></td>'+    
                            '<td><input type="text" name="alamat[]" class="form-control" required=""></td>'+    
                            '<td><input type="text" name="role[]" class="form-control" required=""></td>'+    
                            '<td><input type="text" name="password[]" class="form-control" required=""></td>'+    
                            '<td><a href="#" class="btn btn-danger remove"><i class="glyphicon glyphicon-remove"></i></a></td>'+
                            '</tr>';
                            $('tbody').append(tr);
                        };
                        $('.remove').live('click',function(){
                            var last=$('tbody tr').length;
                            if(last==1){
                                alert("you can not remove last row");
                            }
                            else{
                                $(this).parent().parent().remove();
                            }
                            
                        });
                    </script>
                </body>
                </html> 
=======
                    </div></div>
                    <div class="panel panel-footer" >
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Nama</th>
                                    <th>Email</th>
                                    <th>Nip</th>
                                    <th>Alamat</th>
                                    <th>Bagian</th>
                                    <th>Password</th>
                                    <th><a href="#" class="addRow"><i class="glyphicon glyphicon-plus"></i></a></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td><input type="text" name="name[]" class="form-control" required=""></td>
                                    <td><input type="email" name="email[]" class="form-control" required=""></td>    
                                    <td><input type="text" name="nip[]" class="form-control" required=""></td>    
                                    <td><input type="text" name="alamat[]" class="form-control" required=""></td>    
                                    <td>
                                        <select class="form-control" name="role[]" required>
                                            <option value="">Silahkan Pilih</option>
                                            <option value="1">Admin</option>
                                            <option value="2">Operator</option>
                                            <option value="3">Peminjam</option>
                                        </select>
                                    </td>
                                    <td><input type="text" name="password[]" class="form-control" required=""></td>    
                                    <td><a href="#" class="btn btn-danger remove"><i class="glyphicon glyphicon-remove"></i></a></td>
                                </tr>
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr> 
                                <td style="border: none"></td>
                                <td style="border: none"></td>
                                <td style="border: none"></td>
                                <td style="border: none"></td>
                                <td style="border: none"></td>
                                <td><input type="submit" name="" value="Submit" class="btn btn-success"></td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <a href="{{route('users.index')}}" class="btn btn-warning pull-right">Back</a>
            </section>
        </form>
    </div>
    <script type="text/javascript">
        $('tbody').delegate('.quantity,.budget','keyup',function(){
            var tr=$(this).parent().parent();
            var quantity=tr.find('.quantity').val();
            var budget=tr.find('.budget').val();
            var amount=(quantity*budget);
            tr.find('.amount').val(amount);
            total();
        });
        function total(){
            var total=0;
            $('.amount').each(function(i,e){
                var amount=$(this).val()-0;
                total +=amount;
            });
            $('.total').html(total+".00 tk");    
        }
        $('.addRow').on('click',function(){
            addRow();
        });
        function addRow()
        {
            var tr='<tr>'+
                '<td><input type="text" name="name[]" class="form-control" required=""></td>'+
                '<td><input type="email" name="email[]" class="form-control" required=""></td>'+   
                '<td><input type="text" name="nip[]" class="form-control" required=""></td>'+    
                '<td><input type="text" name="alamat[]" class="form-control" required=""></td>'+    
                '<td><select class="form-control" name="role" required><option value="">Silahkan Pilih</option><option value="1">Admin</option><option value="2">Operator</option><option value="3">Peminjam</option></select></td>'+    
                '<td><input type="text" name="password[]" class="form-control" required=""></td>'+    
                '<td><a href="#" class="btn btn-danger remove"><i class="glyphicon glyphicon-remove"></i></a></td>'+
                '</tr>';
                $('tbody').append(tr);
            };
            $('.remove').live('click',function(){
                var last=$('tbody tr').length;
                if(last==1){
                    alert("you can not remove last row");
                }
                else{
                    $(this).parent().parent().remove();
                }
                
            });
        </script>
    </body>
    </html> 
>>>>>>> third commit

resources/views/users/edit.blade.php
@extends('layouts.transaksi')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                {{-- <div class="panel-heading">Edit User</div> --}}

                <div class="panel-body">	
                <form action="/admin/{{$page}}/{{$user->id}}" method="post">
                    {{csrf_field()}}
                    {{method_field('PUT')}}
                        <div class="form-group">
                            <label>Nama</label>
                            <input type="text" name="name" class="form-control" value="{{$user->name}}">
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            <input type="text" name="email" class="form-control" value="{{$user->email}}">
                        </div>
                        <div class="form-group">
                            <label>Alamat</label>
                            <input type="text" name="alamat" class="form-control" value="{{$user->alamat}}">
                        </div>
                           <div class="form-group">
                            <label>Nip</label>
                            <input type="number" name="nip" class="form-control" value="{{$user->nip}}">
                        </div>
                        <div class="form-group">
                            <label>Password</label>
                            <input type="text" name="password" class="form-control">
                        </div>
                        <div class="form-group"> 
                            <label>Bagian</label>
                        <select class="form-control" name="role" required>
                        <option value="">Silahkan Pilih</option>
                            <option {{$user->role == 1 ? 'selected':''}} value="1">Admin</option>
                            <option {{$user->role == 2 ? 'selected':''}} value="2">Operator</option>
                            <option {{$user->role == 3 ? 'selected':''}} value="3">Peminjam</option>
                        </select>
                        </div>

                        <button type="submit" class="btn btn-primary">Simpan</button>
                        <a href="{{route('users.index')}}" class="btn btn-warning pull-right">Back</a>
                    </form>
	
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/form.blade.php
<div class="form-group">
    <label>Nama</label>
    <input type="text" id="name" name="name" class="form-control">
</div>
<div class="form-group">
    <label>Email</label>
    <input type="text" id="email" name="email" class="form-control">
</div>
<div class="form-group">
    <label>Alamat</label>
    <input type="text" id="alamat" name="alamat" class="form-control">
</div>
   <div class="form-group">
    <label>Nip</label>
    <input type="number" id="nip" name="nip" class="form-control">
</div>
<div class="form-group">
    <label>Password</label>
    <input type="text" id="password" name="password" class="form-control">
</div>
<div class="form-group">
    <label>Bagian</label>
<select class="form-control" id="role" name="role" required>
<option value="">Silahkan Pilih</option>
    <option value="1">Admin</option>
    <option value="2">Operator</option>
    <option value="3">Peminjam</option>
</select>
</div>

resources/views/users/index.blade.php
@extends('layouts.app_admin')
@section('title')
Inventaris | User
@endsection

@section('active-user')
class="active"
@endsection

@section('content')

<div class="panel-header panel-header-sm">
</div>

<div class="content"> 
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title"> Tabel User</h4>
          <a href="{{$page}}/create" class="btn btn-round btn-primary">Tambah User</a>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-borderless" id="table"> 
              <thead> 
                <tr> 
                  <th class = "text-center"> No </th> 
                  <th class = "text-center"> Nama </th> 
                  <th class = "text-center"> Email </th> 
                  <th class = "text-center"> Nip </th> 
                  <th class = "text-center"> Alamat </th> 
                  <th class = "text-center"> Status </th> 
                  <th class = "text-center"> Tindakan </th> 
                </tr> 
              </thead> 
              <tbody> 
                @foreach ($users as $user)
                <tr> 
                  <td> {{$no++}} </td> 
                  <td> {{$user->name}} </td> 
                  <td> {{$user->email}} </td> 
                  <td> {{$user->nip}} </td> 
                  <td> {{$user->alamat}} </td> 
                  <td> 
                    {!!$user->role ==1 ? 'Admin' :''!!}
                    {!!$user->role ==2 ? 'Operator' :''!!}
                    {!!$user->role ==3 ? 'Peminjam' :''!!}
                  </td> 
                  <td>
                    <a href="{{$page.'/'.$user->id.'/edit'}}" class="btn btn-primary"><i class="fal fa-pen"></i></a>
                    <form action="users/{{$user->id}}" method="POST">
                      <input type="hidden" name="_method" value="DELETE">
                      @csrf
                      <button type="submit" class="btn btn-danger"><i class="fal fa-trash"></i></button>
                    </td>
                  </form>
                </tr>
                <!-- Modal -->
                {{-- <div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button> --}}
                        {{-- <h4 class="modal-title" id="myModalLabel">Edit Category</h4> --}}
                      {{-- </div>
                      <form action="/admin/{{$page}}/{{$user->id}}" method="post">
                        {{method_field('patch')}}
                        {{csrf_field()}}
                        <div class="modal-body">  
                          <input type="hidden" name="id" id="id" value="">
                          @include('users.form')
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                          <button type="submit" class="btn btn-primary">Save Changes</button>
                        </div>
                      </form>
                    </div>
                  </div>
                </div> --}}
                {{-- akhir modal --}} 
                @endforeach
              </tbody> 
            </table> 
          </div>
        </div>
      </div> 
    </div>
  </div>
</div>

{{-- <script>
  $('#edit').on('show.bs.modal', function (event) {
    
    var button = $(event.relatedTarget) 
    var name = button.data('myname') 
    var password = button.data('mypassword') 
    var email = button.data('myemail')
    var nip = button.data('mynip') 
    var alamat = button.data('myalamat') 
    var role = button.data('myrole') 
    var modal = $(this)
    
    modal.find('.modal-body #name').val(name);
    modal.find('.modal-body #password').val(password);
    modal.find('.modal-body #email').val(email);
    modal.find('.modal-body #nip').val(nip);
    modal.find('.modal-body #alamat').val(alamat);
    modal.find('.modal-body #role').val(role);
  })
  
</script> --}}

<script>
  $(document).ready(function() {
    $('#table').DataTable();
  } );
</script>
@endsection