routes/web.php
<?php
 
use App\Data;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
 
Route::get('/home', 'HomeController@index')->name('home'); 
Route::get('/', 'HomeController@index'); 

Route::group(['prefix' => 'admin' , 'middleware' => 'admin'], function(){
    Route::Resource('/barang', 'BarangController');
    Route::Resource('/jenis', 'JenisController');
    Route::Resource('/ruang', 'RuangController');
    Route::Resource('/users', 'UserController');

    Route::get('/laporan/trs', 'LaporanController@transaksi');
    Route::get('/laporan/trs/pdf', 'LaporanController@transaksiPdf');
    Route::get('/laporan/trs/excel', 'LaporanController@transaksiExcel');

    Route::get('/laporan/barang', 'LaporanController@barang');
    Route::get('/laporan/barang/pdf', 'LaporanController@barangPdf');
    Route::get('/laporan/barang/excel', 'LaporanController@barangExcel');
});

Route::group(['prefix' => 'operator' , 'middleware' => 'operator'], function(){
    Route::get('/', 'OperatorController@index');
});

Route::Resource('/dashboard','DashboardController');
Route::Resource('/transaksi', 'TransaksiController');

Auth::routes();

app/Transaksi.php
<?php

namespace App;
  
use Illuminate\Database\Eloquent\Model;

class Transaksi extends Model
{
    protected $table = 'transaksi';
    protected $fillable = ['kode_transaksi', 'pegawai_id', 'barang_id', 'tgl_pinjam', 'tgl_kembali', 'status', 'ket'];

    public function User()
    {
    	return $this->belongsTo(User::class,'pegawai_id');
    }
    public function inventaris()
    {
    	return $this->belongsTo(Inventaris::class,'barang_id');
    }

}

app/Http/Controllers/TransaksiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Transaksi;
use App\Inventaris;
use App\User; 
use Auth;

class TransaksiController extends Controller
{

    protected $page = 'transaksi';

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    { 
        $page=$this->page;
        $no = 1;

        if(Auth::user()->role == '3')
        {
            $datas = Transaksi::where('pegawai_id', Auth::user()->id)->get();
        } else {
            $datas = Transaksi::get();
        }
        return view($this->page.'/index',compact('no','page','datas'));    
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
        $getRow = Transaksi::orderBy('id', 'DESC')->get();
        $rowCount = $getRow->count();
        
        $lastId = $getRow->first();
        
        $kode = "TR00001";
        
        if ($rowCount > 0) {
            if ($lastId->id < 9) {
                $kode = "TR0000".''.($lastId->id + 1);
            } else if ($lastId->id < 99) {
                $kode = "TR000".''.($lastId->id + 1);
            } else if ($lastId->id < 999) {
                $kode = "TR00".''.($lastId->id + 1);
            } else if ($lastId->id < 9999) {
                $kode = "TR0".''.($lastId->id + 1);
            } else {
                $kode = "TR".''.($lastId->id + 1);
            }
        }
        
        $barangs = Inventaris::where('jumlah', '>', 0)->get();
        $users = User::get();
        return view('transaksi.create', compact('barangs', 'kode', 'users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'kode_transaksi' => 'required|string|max:255',
            'tgl_pinjam' => 'required',
            'tgl_kembali' => 'required',
            'barang_id' => 'required',
            'pegawai_id' => 'required',

        ]);

        $transaksi = Transaksi::create([
                'kode_transaksi' => $request->get('kode_transaksi'),
                'tgl_pinjam' => $request->get('tgl_pinjam'),
                'tgl_kembali' => $request->get('tgl_kembali'),
                'barang_id' => $request->get('barang_id'),
                'pegawai_id' => $request->get('pegawai_id'),
                'ket' => $request->get('ket'),
                'status' => 'pinjam'
            ]);

        $transaksi->inventaris->where('id', $transaksi->barang_id)
                        ->update([
                            'jumlah' => ($transaksi->inventaris->jumlah - 1),
                            ]);

        return redirect()->route('transaksi.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
        $data = Transaksi::findOrFail($id);


        if((Auth::user()->role == '3')) {
            return redirect()->to('/');
        }


        return view('transaksi.show', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $transaksi = Transaksi::find($id);

        $transaksi->update([    
                'status' => 'kembali'
                ]);

        $transaksi->inventaris->where('id', $transaksi->inventaris->id)
                        ->update([
                            'jumlah' => ($transaksi->inventaris->jumlah + 1),
                            ]);

        return redirect()->route('transaksi.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Transaksi::find($id)->delete();
        return redirect()->route('transaksi.index');
    }
}

resources/views/transaksi/create.blade.php
@section('js')
<script type="text/javascript">
  $(document).on('click', '.pilih', function (e) {
    document.getElementById("barang_nama").value = $(this).attr('data-barang_nama');
    document.getElementById("barang_id").value = $(this).attr('data-barang_id');
    $('#myModal').modal('hide');
  });
  
  $(document).on('click', '.pilih_pegawai', function (e) {
    document.getElementById("pegawai_id").value = $(this).attr('data-pegawai_id');
    document.getElementById("pegawai_nama").value = $(this).attr('data-pegawai_name');
    $('#myModal2').modal('hide');
  });
  
  $(function () {
    $("#lookup, #lookup2").dataTable();
  });
  
</script>

@stop 
@section('css')

@stop
@extends('layouts.transaksi')
 
@section('content')

<form method="POST" action="{{ route('transaksi.store') }}" enctype="multipart/form-data">
  {{ csrf_field() }}
  <div class="row">
    <div class="col-md-12 d-flex align-items-stretch grid-margin">
      <div class="row flex-grow">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Tambah Transaksi baru</h4>
              
              <div class="form-group{{ $errors->has('kode_transaksi') ? ' has-error' : '' }}">
                <label for="kode_transaksi" class="col-md-4 control-label">Kode Transaksi</label>
                <div class="col-md-6">
                  <input id="kode_transaksi" type="text" class="form-control" name="kode_transaksi" value="{{ $kode }}" required readonly="">
                  @if ($errors->has('kode_transaksi'))
                  <span class="help-block">
                    <strong>{{ $errors->first('kode_transaksi') }}</strong>
                  </span>
                  @endif
                </div>
              </div>
              <div class="form-group{{ $errors->has('tgl_pinjam') ? ' has-error' : '' }}">
                <label for="tgl_pinjam" class="col-md-4 control-label">Tanggal Pinjam</label>
                <div class="col-md-3">
                  <input id="tgl_pinjam" type="date" class="form-control" name="tgl_pinjam" value="{{ date('Y-m-d', strtotime(Carbon\Carbon::today()->toDateString())) }}" required @if(Auth::user()->level == 'user') readonly @endif>
                  @if ($errors->has('tgl_pinjam'))
                  <span class="help-block">
                    <strong>{{ $errors->first('tgl_pinjam') }}</strong>
                  </span>
                  @endif
                </div>
              </div>
              <div class="form-group{{ $errors->has('tgl_kembali') ? ' has-error' : '' }}">
                <label for="tgl_kembali" class="col-md-4 control-label">Tanggal Kembali</label>
                <div class="col-md-3">
                  <input id="tgl_kembali" type="date"  class="form-control" name="tgl_kembali" value="{{ date('Y-m-d', strtotime(Carbon\Carbon::today()->addDays(5)->toDateString())) }}" required="" @if(Auth::user()->level == 'user') readonly @endif>
                  @if ($errors->has('tgl_kembali'))
                  <span class="help-block">
                    <strong>{{ $errors->first('tgl_kembali') }}</strong>
                  </span>
                  @endif
                </div>
              </div>
              
              <div class="form-group{{ $errors->has('barang_id') ? ' has-error' : '' }}">
                <label for="barang_id" class="col-md-4 control-label">Barang</label>
                <div class="col-md-6">
                  <div class="input-group">
                    <input id="barang_nama" type="text" class="form-control" readonly="" required>
                    <input id="barang_id" type="hidden" name="barang_id" value="{{ old('barang_id') }}" required readonly="">
                    <span class="input-group-btn">
                      <button type="button" class="btn btn-info btn-secondary" data-toggle="modal" data-target="#myModal"><b>Cari Barang</b> <span class="fa fa-search"></span></button>
                    </span>
                  </div>
                  @if ($errors->has('barang_id'))
                  <span class="help-block">
                    <strong>{{ $errors->first('barang_id') }}</strong>
                  </span>
                  @endif
                  
                </div>
              </div>
              
              
              @if(Auth::user()->role == '1'||Auth::user()->role == '2')
              <div class="form-group{{ $errors->has('pegawai_id') ? ' has-error' : '' }}">
                <label for="pegawai_id" class="col-md-4 control-label">Pegawai</label>
                <div class="col-md-6">
                  <div class="input-group">
                    <input id="pegawai_nama" type="text" class="form-control" readonly="" required>
                    <input id="pegawai_id" type="hidden" name="pegawai_id" value="{{ old('pegawai_id') }}" required readonly="">
                    <span class="input-group-btn">
                      <button type="button" class="btn btn-warning btn-secondary" data-toggle="modal" data-target="#myModal2"><b>Cari pegawai</b> <span class="fa fa-search"></span></button>
                    </span>
                  </div>
                  @if ($errors->has('pegawai_id'))
                  <span class="help-block">
                    <strong>{{ $errors->first('pegawai_id') }}</strong>
                  </span>
                  @endif
                  
                </div>
              </div>
              @else
              <div class="form-group{{ $errors->has('pegawai_id') ? ' has-error' : '' }}">
                <label for="pegawai_id" class="col-md-4 control-label">Pegawai</label>
                <div class="col-md-6">
                  <input id="pegawai_nama" type="text" class="form-control" readonly="" value="{{Auth::user()->name}}" required>
                  <input id="pegawai_id" type="hidden" name="pegawai_id" value="{{ Auth::user()->id }}" required readonly="">
                  
                  @if ($errors->has('pegawai_id'))
                  <span class="help-block">
                    <strong>{{ $errors->first('pegawai_id') }}</strong>
                  </span>
                  @endif
                  
                </div>
              </div>
              @endif
              
              <div class="form-group{{ $errors->has('ket') ? ' has-error' : '' }}">
                <label for="ket" class="col-md-4 control-label">Keterangan</label>
                <div class="col-md-6">
                  <input id="ket" type="text" class="form-control" name="ket" value="{{ old('ket') }}">
                  @if ($errors->has('ket'))
                  <span class="help-block">
                    <strong>{{ $errors->first('ket') }}</strong>
                  </span>
                  @endif
                </div>
              </div>
              
              <button type="submit" class="btn btn-primary" id="submit">
                Submit
              </button>
              <button type="reset" class="btn btn-danger">
                Reset
              </button>
              <a href="{{route('transaksi.index')}}" class="btn btn-light pull-right">Back</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    
  </div>
</form>


<!-- Modal -->
<div class="modal fade bd-example-modal-lg" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" >
  <div class="modal-dialog modal-lg" role="document" >
    <div class="modal-content" style="background: #fff;">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Cari Barang</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <table id="lookup" class="table table-bordered table-hover table-striped">
          <thead>
            <tr>
              <th>Nama</th>
              <th>Kode</th>
              <th>Kondisi</th>
              <th>Keterangan</th>
              <th>Stok</th>
            </tr>
          </thead>
          <tbody>
            @foreach($barangs as $data)
            <tr class="pilih" data-barang_id="<?php echo $data->id; ?>" data-barang_nama="<?php echo $data->nama; ?>" >
              <td>{{$data->nama}}</td>
                <td>{{$data->kode_inventaris}}</td>
                <td>{{$data->kondisi}}</td>
                <td>{{$data->keterangan}}</td>
                <td>{{$data->jumlah}}</td>
              </tr>
              @endforeach
            </tbody>
          </table>  
        </div>
      </div>
    </div>
  </div>
  
  
  <!-- Modal -->
  <div class="modal fade bd-example-modal-lg" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" >
    <div class="modal-dialog modal-lg" role="document" >
      <div class="modal-content" style="background: #fff;">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Cari pegawai</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <table id="lookup" class="table table-bordered table-hover table-striped">
            <thead>
              <tr>
                <th>
                  Nama
                </th>
                <th>
                  Nip 
                </th>
                <th>
                  Email
                </th>
                <th> 
                  Bagian
                </th>
              </tr>
            </thead>
            <tbody>
              @foreach($users as $data)
              <tr class="pilih_pegawai" data-pegawai_id="<?php echo $data->id; ?>" data-pegawai_name="<?php echo $data->name; ?>" >
                <td class="py-1">
                  {{$data->name}}
                </td>
                <td>
                  {{$data->nip}}
                </td>
                
                <td>
                  {{$data->email}}
                  
                </td>
                <td>
                  {{$data->role}}
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>  
        </div>
      </div>
    </div>
  </div>
  @endsection

resources/views/transaksi/index.blade.php
@section('js')
@stop

@extends('layouts.app_admin')

@section('active-transaksi')
  class="active"
@endsection

@section('title')
Inventaris | Transaksi
@endsection

@if (auth::user()->role==1 || auth::user()->role==2)
  @section('navbar_name')
    Inventaris Transaksi
  @endsection
@endif

@if (auth::user()->role==3)
  @section('navbar_name')
    <a href="{{url('/dashboard')}}" class="btn btn-round btn-warning">Ke Halaman Dashboard</a>
  @endsection
@endif
 

@section('content')

<div class="panel-header panel-header-sm">
</div>

<div class="content"> 
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title"> Tabel Transaksi</h4>
          <a href="{{$page}}/create" class="btn btn-round btn-primary">Tambah Transaksi</a>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-borderless" id="table"> 
              <thead> 
                <tr> 
                  <th class = "text-center"> Kode </th> 
                  <th class = "text-center"> Barang </th> 
                  <th class = "text-center"> Peminjam </th> 
                  <th class = "text-center"> Tgl Pinjam </th> 
                  <th class = "text-center"> Tgl Kembali </th> 
                  <th class = "text-center"> Status </th> 
                  <th class = "text-center"> Aksi </th> 
                </tr> 
              </thead>   
              <tbody> 
                @foreach ($datas as $data)
                <tr> 
                  <td> {{$data->kode_transaksi}} </td> 
                  <td> {{$data->inventaris->nama}} </td> 
                  <td> {{$data->user->name}} </td> 
                  <td> {{$data->tgl_pinjam}} </td> 
                  <td> {{$data->tgl_kembali}} </td> 
                  <td>
                      @if($data->status == 'pinjam')
                        <label class="badge badge-warning">Pinjam</label>
                      @else
                        <label class="badge badge-success">Kembali</label>
                      @endif
                      </td>
                      <td>
                      @if(Auth::user()->role == '1')
                      <div class="btn-group dropdown">
                      <button type="button" class="btn btn-success dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Action
                      </button>
                      <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 30px, 0px);">
                      @if($data->status == 'pinjam')
                      <form action="{{ route('transaksi.update', $data->id) }}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        {{ method_field('put') }}
<<<<<<< HEAD
                        <button class="dropdown-item" onclick="return confirm('Anda yakin data ini sudah kembali?')"> Sudah Kembali
=======
                        <button class="dropdown-item" onclick="return confirm('Anda yakin data ini Kembalikan?')"> Kembalikan
>>>>>>> third commit
                        </button>
                      </form>
                      @endif
                        <form action="{{ route('transaksi.destroy', $data->id) }}" class="pull-left"  method="post">
                        {{ csrf_field() }}
                        {{ method_field('delete') }}
                        <button class="dropdown-item" onclick="return confirm('Anda yakin ingin menghapus data ini?')"> Delete
                        </button>
                      </form>
                      </div>
                    </div>
                    @endif

                    @if(Auth::user()->role == '2') 
                      @if($data->status == 'pinjam')
                        <form action="{{ route('transaksi.update', $data->id) }}" method="post" enctype="multipart/form-data">
                          {{ csrf_field() }}
                          {{ method_field('put') }}
<<<<<<< HEAD
                          <button class="btn btn-info btn-xs" onclick="return confirm('Anda yakin data ini sudah kembali?')">Sudah Kembali
=======
                          <button class="btn btn-info btn-xs" onclick="return confirm('Anda yakin data ini Kembalikan?')">Kembalikan
>>>>>>> third commit
                          </button>
                        </form>
                        @else
                        -
                      @endif
                    @endif
                    
                    @if(Auth::user()->role == '3')
                      @if($data->status == 'pinjam')
                        -
                        @else
                        -
                      @endif
                    @endif
                      </td>
                    </tr>
                  @endforeach
            </tbody> 
          </table> 
            </div>
            {{--  {!! $datas->links() !!} --}}
          </div>
        </div> 
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function() {
    $('#table').DataTable({
      "iDisplayLength": 10
    });
  });
</script>
@endsection
  

resources/views/transaksi/show.blade.php
@extends('layouts.transaksi')

@section('content')

<div class="row">
            <div class="col-md-12 d-flex align-items-stretch grid-margin">
              <div class="row flex-grow">
                <div class="col-12">
                  <div class="card">
                    <div class="card-body">
                      <h4 class="card-title">Detail <b>{{$data->kode_transaksi}}</b></h4>
                        <div class="form-group{{ $errors->has('kode_transaksi') ? ' has-error' : '' }}">
                            <label for="kode_transaksi" class="col-md-4 control-label">Kode Transaksi</label>
                            <div class="col-md-6">
                                <input id="kode_transaksi" type="text" class="form-control" name="kode_transaksi" value="{{$data->kode_transaksi}}" required readonly="">
                            </div>
                        </div>
                         <div class="form-group{{ $errors->has('tgl_pinjam') ? ' has-error' : '' }}">
                            <label for="tgl_pinjam" class="col-md-4 control-label">Tanggal Pinjam</label>
                            <div class="col-md-3">
                                <input id="tgl_pinjam" type="date" class="form-control" name="created_at" value="{{ date('Y-m-d', strtotime($data->created_at)) }}" readonly="">
                            </div>
                        </div>
                         <div class="form-group{{ $errors->has('tgl_kembali') ? ' has-error' : '' }}">
                            <label for="tgl_kembali" class="col-md-4 control-label">Tanggal Kembali</label>
                            <div class="col-md-3">
                                <input id="tgl_kembali" type="date"  class="form-control" name="updated_at" value="{{ date('Y-m-d', strtotime($data->updated_at)) }}" readonly="">
                            </div>
                        </div>


                        <div class="form-group">
                            <label for="barang" class="col-md-4 control-label">Barang</label>
                            <div class="col-md-6">
                                <input id="barang" type="text" class="form-control" readonly="" value="{{$data->inventaris->nama}}">

                            </div>
                        </div>

                        <div class="form-group">
                            <label for="pegawai" class="col-md-4 control-label">Anggota</label>
                            <div class="col-md-6">
                                <input id="pegawai" type="text" class="form-control" readonly="" value="{{$data->user->name}}">

                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('ket') ? ' has-error' : '' }}">
                            <label for="ket" class="col-md-4 control-label">Status</label>
                            <div class="col-md-6">
                                @if($data->status == 'pinjam')
                                  <label class="badge badge-warning">Pinjam</label>
                                @else
                                  <label class="badge badge-success">Kembali</label>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('ket') ? ' has-error' : '' }}">
                            <label for="ket" class="col-md-4 control-label">Keterangan</label>
                            <div class="col-md-6">
                                <input id="ket" type="text" class="form-control" name="ket" value="{{ $data->ket }}" readonly="">
                            </div>
                        </div>

                        <a href="{{route('transaksi.index')}}" class="btn btn-light pull-right">Back</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>

</div>


@endsection