routes/web.php
<?php
 
use App\Data;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
 
Route::get('/home', 'HomeController@index')->name('home'); 
Route::get('/', 'HomeController@index'); 

Route::group(['prefix' => 'admin' , 'middleware' => 'admin'], function(){
    Route::Resource('/barang', 'BarangController');
    Route::Resource('/jenis', 'JenisController');
    Route::Resource('/ruang', 'RuangController');
    Route::Resource('/users', 'UserController');

    Route::get('/laporan/trs', 'LaporanController@transaksi');
    Route::get('/laporan/trs/pdf', 'LaporanController@transaksiPdf');
    Route::get('/laporan/trs/excel', 'LaporanController@transaksiExcel');

    Route::get('/laporan/barang', 'LaporanController@barang');
    Route::get('/laporan/barang/pdf', 'LaporanController@barangPdf');
    Route::get('/laporan/barang/excel', 'LaporanController@barangExcel');
});

Route::group(['prefix' => 'operator' , 'middleware' => 'operator'], function(){
    Route::get('/', 'OperatorController@index');
});

Route::Resource('/dashboard','DashboardController');
Route::Resource('/transaksi', 'TransaksiController');

Auth::routes();

app/Ruang.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ruang extends Model
{
    protected $table="ruang";
    public $guarded = [];
    public $timestamps = false;

    public function inventaris()
    {
    	return $this->belongsTo(Inventaris::class);
    }
}

app/Http/Controllers/RuangController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Ruang;

class RuangController extends Controller
{
    protected $page = 'ruang';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ruang = Ruang::all();
        $no = 1;
        $page = $this->page;
        return view($this->page.'/index',compact('page','ruang','no'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $page = $this->page;
        return view($this->page.'/create',compact('page'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data=$request->all();
        
        if(count($request->nama_ruang) > 0)
        {
            foreach($request->nama_ruang as $item=>$v){
                $data2=array(
                    'nama_ruang'=>$request->nama_ruang[$item],
                    'kode_ruang'=>$request->kode_ruang[$item],
                    'keterangan'=>$request->keterangan[$item],
                );
                Ruang::insert($data2);
            }
        }
        return redirect('/admin/ruang');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ruang = Ruang::find($id);
        $page = $this->page;
        return view($this->page.'/edit',compact('ruang','page'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Ruang::whereId($id)->update([
            'nama_ruang' => $request->nama_ruang,
            'kode_ruang' => $request->kode_ruang,
            'keterangan' => $request->keterangan,
        ]);

        return redirect('/admin/'.$this->page);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
            
        Ruang::destroy($id);
        return redirect('/admin/ruang');
    }
}

resources/views/ruang/create.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Multiple data send</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
</head>
<body>
    <div class="container">
        <br>
        @if(Session::has('success'))
        <div class="alert alert-success">
            {{Session::get('success')}}
        </div>
        @endif
        <form action="/admin/ruang" method="POST">
            {{csrf_field()}}
            <section>
                <div class="panel panel-header">
                    
                    <div class="row">
                            </div></div>
                            <div class="panel panel-footer" >
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Nama Ruang</th>
                                            <th>Kode Ruang</th>
                                            <th>Keterangan</th>
                                            <th><a href="#" class="addRow"><i class="glyphicon glyphicon-plus"></i></a></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td><input type="text" name="nama_ruang[]" class="form-control" required=""></td>
                                                <td><input type="text" name="kode_ruang[]" class="form-control" required=""></td>    
                                                <td><input type="text" name="keterangan[]" class="form-control" required=""></td>    
                                                <td><a href="#" class="btn btn-danger remove"><i class="glyphicon glyphicon-remove"></i></a></td>
                                            </tr>
                                        </tr>
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <td style="border: none"></td>
                                            <td style="border: none"></td>
<<<<<<< HEAD
                                            <td style="border: none"></td>
=======
>>>>>>> third commit
                                            <td><input type="submit" name="" value="Submit" class="btn btn-success"></td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
<<<<<<< HEAD
=======
                            <a href="{{route('ruang.index')}}" class="btn btn-warning pull-right">Back</a>
>>>>>>> third commit
                        </section>
                    </form>
                </div>
                <script type="text/javascript">
                    $('tbody').delegate('.quantity,.budget','keyup',function(){
                        var tr=$(this).parent().parent();
                        var quantity=tr.find('.quantity').val();
                        var budget=tr.find('.budget').val();
                        var amount=(quantity*budget);
                        tr.find('.amount').val(amount);
                        total();
                    });
                    function total(){
                        var total=0;
                        $('.amount').each(function(i,e){
                            var amount=$(this).val()-0;
                            total +=amount;
                        });
                        $('.total').html(total+".00 tk");    
                    }
                    $('.addRow').on('click',function(){
                        addRow();
                    });
                    function addRow()
                    {
                        var tr='<tr>'+
                            '<td><input type="text" name="nama_ruang[]" class="form-control" required=""></td>'+
                            '<td><input type="text" name="kode_ruang[]" class="form-control" required=""></td>'+   
                            '<td><input type="text" name="keterangan[]" class="form-control" required=""></td>'+    
                            '<td><a href="#" class="btn btn-danger remove"><i class="glyphicon glyphicon-remove"></i></a></td>'+
                            '</tr>';
                            $('tbody').append(tr);
                        };
                        $('.remove').live('click',function(){
                            var last=$('tbody tr').length;
                            if(last==1){
                                alert("you can not remove last row");
                            }
                            else{
                                $(this).parent().parent().remove();
                            }
                            
                        });
                    </script>
                </body>
                </html> 

resources/views/ruang/edit.blade.php
@extends('layouts.transaksi')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Edit Ruang</div>

                <div class="panel-body">	
                <form action="/admin/{{$page}}/{{$ruang->id}}" method="post">
                    {{csrf_field()}}
                    {{method_field('PUT')}}
                        <div class="form-group">
                            <label>Nama</label>
                            <input type="text" name="nama_ruang" class="form-control" value="{{$ruang->nama_ruang}}">
                        </div>
                        <div class="form-group">
                            <label>Kode Ruang</label>
                            <input type="text" name="kode_ruang" class="form-control" value="{{$ruang->kode_ruang}}">
                        </div>
                        <div class="form-group">
                            <label>Keterangan</label>
                            <input type="text" name="keterangan" class="form-control" value="{{$ruang->keterangan}}">
                        </div>
                        <button type="submit" class="btn btn-primary">Simpan</button>
                        <a href="{{route('ruang.index')}}" class="btn btn-warning pull-right">Back</a>
                    </form>
	
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/ruang/index.blade.php
@extends('layouts.app_admin')
@section('title')
    Inventaris | Ruang
@endsection

@section('active-ruang')
  class="active"
@endsection
  
@section('content')
<div class="panel-header panel-header-sm">
</div>
<div class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title"> Contoh Tabel Ruang</h4>
          <a href="{{$page}}/create" class="btn btn-round btn-primary">Tambah Data Ruangan</a>
        </div>
        <div class="card-body">
          <div class="table-responsive">
              <table class="table table-borderless" id = "table"> 
                  <thead> 
                    <tr> 
                      <th class = "text-center"> No </th> 
                      <th class = "text-center"> Nama Ruang </th> 
                      <th class = "text-center"> Kode Ruang </th> 
                      <th class = "text-center"> Keterangan </th> 
                      <th class = "text-center"> Tindakan </th> 
                    </tr> 
                  </thead>  
                  <tbody> 
                    @foreach ($ruang as $ruang)
                    <tr> 
                      <td> {{$no++}} </td> 
                      <td class = "text-center"> {{$ruang->nama_ruang}} </td> 
                      <td class = "text-center"> {{$ruang->kode_ruang}} </td> 
                      <td class = "text-center"> {{$ruang->keterangan}} </td>
                      <td>
                      <a href="{{$page.'/'.$ruang->id.'/edit'}}" class="btn btn-primary"><i class="fal fa-pen"></i></a>
                    <form action="ruang/{{$ruang->id}}" method="POST">
                      <input type="hidden" name="_method" value="DELETE">
                      @csrf
                      <button type="submit" class="btn btn-danger"><i class="fal fa-trash"></i></button>
                     </td>
                  </tr> 
                </form>
                    @endforeach
                  </tbody> 
              </table> 
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
    $(document).ready(function() {
      $('#table').DataTable();
  } );
</script>
@endsection