routes/web.php
<?php
 
use App\Data;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
 
Route::get('/home', 'HomeController@index')->name('home'); 
Route::get('/', 'HomeController@index'); 

Route::group(['prefix' => 'admin' , 'middleware' => 'admin'], function(){
    Route::Resource('/barang', 'BarangController');
    Route::Resource('/jenis', 'JenisController');
    Route::Resource('/ruang', 'RuangController');
    Route::Resource('/users', 'UserController');

    Route::get('/laporan/trs', 'LaporanController@transaksi');
    Route::get('/laporan/trs/pdf', 'LaporanController@transaksiPdf');
    Route::get('/laporan/trs/excel', 'LaporanController@transaksiExcel');

    Route::get('/laporan/barang', 'LaporanController@barang');
    Route::get('/laporan/barang/pdf', 'LaporanController@barangPdf');
    Route::get('/laporan/barang/excel', 'LaporanController@barangExcel');
});

Route::group(['prefix' => 'operator' , 'middleware' => 'operator'], function(){
    Route::get('/', 'OperatorController@index');
});

Route::Resource('/dashboard','DashboardController');
Route::Resource('/transaksi', 'TransaksiController');

Auth::routes();

app/Http/Controllers/BarangController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
Use App\Inventaris;
Use App\jenis;
Use App\Ruang;
Use App\User;

class BarangController extends Controller
{

    protected $page = 'barang';
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    { 
        $barang = Inventaris::all();
        $no = 1;
        $page=$this->page;
        return view($this->page.'/index',compact('barang','no','page'));
    }

    /** 
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::get();
        $ruangs = Ruang::get();
        $jeniss = Jenis::get();        

        $page = $this->page;
        return view($this->page.'/create',compact('page','users','ruangs','jeniss')); 
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data=$request->all();
        
        if(count($request->nama) > 0)
        {
            foreach($request->nama as $item=>$v){
                $data2=array(
                    'nama'=>$request->nama[$item],
                    'kode_inventaris'=>$request->kode_inventaris[$item],
                    'kondisi'=>$request->kondisi[$item],
                    'keterangan'=>$request->keterangan[$item],
                    'jumlah'=>$request->jumlah[$item],
                    'id_jenis'=>$request->id_jenis[$item],
                    'id_ruang'=>$request->id_ruang[$item],
                    'pegawai_id'=>$request->pegawai_id[$item],
                );
                Inventaris::insert($data2);
            }
        }
        return redirect('/admin/barang');
    }

    /**
     * Display the specified resource.
     * 
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    { 
        $users = User::get();
        $barang = Inventaris::find($id);
        $page = $this->page;
        return view($this->page.'/edit',compact('barang','page','users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Inventaris::whereId($id)->update([
            'nama' => $request->nama,
            'kode_inventaris' => $request->kode_inventaris,
            'kondisi' => $request->kondisi,
            'keterangan' => $request->keterangan,
            'jumlah' => $request->jumlah,
            'id_jenis' => $request->id_jenis,
            'id_ruang' => $request->id_ruang,
            'pegawai_id' => $request->pegawai_id,
        ]);

        return redirect('/admin/'.$this->page);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Inventaris::destroy($id);
        return redirect('admin/barang');
    }
}

resources/views/barang/create.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Multiple data send</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
</head>
<body>
    <div class="container">
        <br>
        @if(Session::has('success'))
        <div class="alert alert-success">
            {{Session::get('success')}}
        </div>
        @endif
        <form action="/admin/barang" method="POST">
            {{csrf_field()}}
            <section>
                <div class="panel panel-header">
                    
                    <div class="row">
                        {{-- <div class="col-md-6">
                            <div class="form-group">
                                <input type="text" name="customer_name" class="form-control" placeholder="Please enter your name">
                            </div></div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" name="customer_address" class="form-control" placeholder="Please enter your Address">
                                </div></div> --}}
                            </div></div>
                            <div class="panel panel-footer" >
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Nama Barang</th>
                                            <th>Kode Barang</th>
                                            <th>Kondisi</th>
                                            <th>Keterangan</th>
                                            <th>Jumlah</th>
                                            <th>Jenis</th>
                                            <th>Ruang</th>
                                            <th>Pemasok Barang</th>
                                            {{--  <th>Budget</th>
                                                <th>Amount</th> --}}
<<<<<<< HEAD
                                            <th><a href="#" class="addRow"><i class="glyphicon glyphicon-plus"></i></a></th>
=======
                                                <th><a href="#" class="addRow"><i class="glyphicon glyphicon-plus"></i></a></th>
>>>>>>> third commit
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td><input type="text" name="nama[]" class="form-control" required=""></td>
                                                <td><input type="text" name="kode_inventaris[]" class="form-control" required=""></td>    
                                                <td><input type="text" name="kondisi[]" class="form-control" required=""></td>    
                                                <td><input type="text" name="keterangan[]" class="form-control" required=""></td>    
                                                <td><input type="number" name="jumlah[]" class="form-control quantity" required=""></td>
                                                <td> 
                                                    <select class="form-control" id="jenis" name="id_jenis[]" required>
                                                        <option value="">Silahkan Pilih</option>
                                                        @foreach($jeniss as $jenis)
<<<<<<< HEAD
                                                            <option value="{{$jenis->id}}"> {{$jenis->nama_jenis}} </option>
=======
                                                        <option value="{{$jenis->id}}"> {{$jenis->nama_jenis}} </option>
>>>>>>> third commit
                                                        @endforeach
                                                    </select>
                                                </td>
                                                <td> 
                                                    <select class="form-control" id="ruang" name="id_ruang[]" required>
                                                        <option value="">Silahkan Pilih</option>
                                                        @foreach($ruangs as $ruang)
<<<<<<< HEAD
                                                            <option value="{{$jenis->id}}"> {{$ruang->nama_ruang}} </option>
=======
                                                        <option value="{{$jenis->id}}"> {{$ruang->nama_ruang}} </option>
>>>>>>> third commit
                                                        @endforeach
                                                    </select>
                                                </td>
                                                <td> 
                                                    <select class="form-control" id="pegawai" name="pegawai_id[]" required>
                                                        <option value="">Silahkan Pilih</option>
                                                        @foreach($users as $user)
<<<<<<< HEAD
                                                            <option value="{{$jenis->id}}"> {{$user->name}} </option>
=======
                                                        <option value="{{$jenis->id}}"> {{$user->name}} </option>
>>>>>>> third commit
                                                        @endforeach
                                                    </select>
                                                </td>
                                                {{-- <td><input type="number" name="budget[]" class="form-control budget" required=""></td>
                                                <td><input type="text" name="amount[]" class="form-control amount" disabled></td> --}}
                                                <td><a href="#" class="btn btn-danger remove"><i class="glyphicon glyphicon-remove"></i></a></td>
                                            </tr>
                                        </tr>
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <td style="border: none"></td>
                                            <td style="border: none"></td>
                                            <td style="border: none"></td>
                                            <td style="border: none"></td>
                                            <td style="border: none"></td>
                                            <td style="border: none"></td>
                                            <td style="border: none"></td>
                                            {{--  <td style="border: none"></td>
                                            <td>Total</td>
                                            <td><b class="total"></b> </td> --}}
                                            <td><input type="submit" name="" value="Submit" class="btn btn-success"></td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
<<<<<<< HEAD
=======
                            <a href="{{route('barang.index')}}" class="btn btn-warning pull-right">Back</a>
>>>>>>> third commit
                        </section>
                    </form>
                </div>
                <script type="text/javascript">
                    $('tbody').delegate('.quantity,.budget','keyup',function(){
                        var tr=$(this).parent().parent();
                        var quantity=tr.find('.quantity').val();
                        var budget=tr.find('.budget').val();
                        var amount=(quantity*budget);
                        tr.find('.amount').val(amount);
                        total();
                    });
                    function total(){
                        var total=0;
                        $('.amount').each(function(i,e){
                            var amount=$(this).val()-0;
                            total +=amount;
                        });
                        $('.total').html(total+".00 tk");    
                    }
                    $('.addRow').on('click',function(){
                        addRow();
                    });
                    function addRow()
                    {
                        var tr='<tr>'+
                            '<td><input type="text" name="nama[]" class="form-control" required=""></td>'+
                            '<td><input type="text" name="kode_inventaris[]" class="form-control" required=""></td>'+   
                            '<td><input type="text" name="kondisi[]" class="form-control" required=""></td>'+    
                            '<td><input type="text" name="keterangan[]" class="form-control" required=""></td>'+    
                            '<td><input type="number" name="jumlah[]" class="form-control quantity" required=""></td>'+
                            '<td><select class="form-control" id="jenis" name="id_jenis[]" required><option value="">Silahkan Pilih</option>@foreach($jeniss as $jenis)<option value="{{$jenis->id}}"> {{$jenis->nama_jenis}} </option>@endforeach</select></td>'+
                            '<td><select class="form-control" id="ruang" name="id_ruang[]" required><option value="">Silahkan Pilih</option>@foreach($ruangs as $ruang)<option value="{{$ruang->id}}"> {{$ruang->nama_ruang}} </option>@endforeach</select></td>'+
                            '<td><select class="form-control" id="pegawai" name="pegawai_id[]" required><option value="">Silahkan Pilih</option>@foreach($users as $user)<option value="{{$user->id}}"> {{$user->name}} </option>@endforeach</select></td>'+
                            /* '<td><input type="number" name="budget[]" class="form-control budget" required=""></td>'+
                            '<td><input type="text" name="amount[]" class="form-control amount" disabled></td>'+ */
                            '<td><a href="#" class="btn btn-danger remove"><i class="glyphicon glyphicon-remove"></i></a></td>'+
                            '</tr>';
                            $('tbody').append(tr);
                        };
                        $('.remove').live('click',function(){
                            var last=$('tbody tr').length;
                            if(last==1){
                                alert("you can not remove last row");
                            }
                            else{
                                $(this).parent().parent().remove();
                            }
                            
                        });
                    </script>
                </body>
                </html> 

resources/views/barang/edit.blade.php
@extends('layouts.transaksi')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                {{-- <div class="panel-heading">Edit barang</div> --}}

                <div class="panel-body">	
                <form action="/admin/{{$page}}/{{$barang->id}}" method="post">
                    {{csrf_field()}}
                    {{method_field('PUT')}}
                        <div class="form-group">
                            <label>Nama Barang</label>
                            <input type="text" name="nama" class="form-control" value="{{$barang->nama}}">
                        </div>
                        <div class="form-group">
                            <label>Kode Inventaris</label>
                            <input type="text" name="kode_inventaris" class="form-control" value="{{$barang->kode_inventaris}}">
                        </div>
                        <div class="form-group">
                            <label>Kondisi</label>
                            <input type="text" name="kondisi" class="form-control" value="{{$barang->kondisi}}">
                        </div>
                           <div class="form-group">
                            <label>Keterangan</label>
                            <input type="text" name="keterangan" class="form-control" value="{{$barang->keterangan}}">
                        </div>
                        <div class="form-group">
                            <label>Jumlah</label>
                            <input type="text" name="jumlah" class="form-control" value="{{$barang->jumlah}}">
                        </div>
                        <div class="form-group">
                            <label>Jenis</label>
                            <input type="text" name="id_jenis" class="form-control" value="{{$barang->id_jenis}}">
                        </div>
                        <div class="form-group">
                            <label>Ruang</label>
                            <input type="text" name="id_ruang" class="form-control" value="{{$barang->id_ruang}}">
                    </div> 
                        <div class="form-group">
                            <label>Pemasok</label>
                            <select class="form-control" id="jenis" name="id_jenis[]" required>
                                <option value="">Silahkan Pilih</option>
                                @foreach($users as $user)
                                    <option value="{{$user->id}}"> {{$user->name}} </option>
                                @endforeach
                            </select>
                        </div>

                        <button type="submit" class="btn btn-primary">Simpan</button>
                        <a href="{{route('barang.index')}}" class="btn btn-warning pull-right">Back</a>
                    </form>
	
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/barang/index.blade.php
@extends('layouts.app_admin')
@section('title')
Inventaris | Barang
@endsection
@section('active-barang')
class="active"
@endsection
@section('content')
<div class="panel-header panel-header-sm">
</div>
<div class="content">
  <div class="row"> 
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Tabel Barang</h4>
          <a href="{{$page}}/create" class="btn btn-round btn-primary">Tambah Barang</a>
          <!-- Button trigger modal -->
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-borderless" id="table"> 
              <thead> 
                <tr> 
                  <th class = "text-center"> No </th> 
                  <th class = "text-center"> Nama Barang </th> 
                  <th class = "text-center"> Kode Barang </th> 
                  <th class = "text-center"> Kondisi </th> 
                  <th class = "text-center"> Keterangan </th> 
                  <th class = "text-center"> Jumlah </th> 
                  <th class = "text-center"> Jenis </th> 
                  <th class = "text-center"> Tanggal Masuk </th> 
                  <th class = "text-center"> Ruang </th> 
                  <th class = "text-center"> Pemasuk barang </th> 
                  <th class = "text-center"> Tindakan </th> 
                </tr> 
              </thead> 
              <tbody> 
                @foreach ($barang as $barang)
                <tr>  
                  <td> {{$no++}} </td> 
                  <td> {{$barang->nama}} </td> 
                  <td> {{$barang->kode_inventaris}} </td> 
                  <td> {{$barang->kondisi}} </td> 
                  <td> {{$barang->keterangan}} </td> 
                  <td> {{$barang->jumlah}} </td> 
                  <td> {{$barang->jenis->nama_jenis}} </td> 
                  <td> {{$barang->created_at}} </td> 
                  <td> {{$barang->ruang->nama_ruang}} </td> 
                  <td> 
                      {{$barang->user->name}}
                  </td> 
                  <td>
                    <a href="{{$page.'/'.$barang->id.'/edit'}}" class="btn btn-primary"><i class="fal fa-pen"></i></a>
                    <form action="barang/{{$barang->id}}" method="POST">
                      <input type="hidden" name="_method" value="DELETE">
                      @csrf
                      <button type="submit" class="btn btn-danger"><i class="fal fa-trash"></i></button>
                    </td>
                  </tr> 
                </form>
                @endforeach
              </tbody> 
            </table> 
          </div>
        </div>
      </div> 
    </div>
  </div>
</div>
<script>
  $(document).ready(function() {
    $('#table').DataTable();
  } );
</script>
@endsection